# Generated by Django 2.2.10 on 2020-10-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('filiere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enseignant', models.CharField(default='test', max_length=5)),
                ('titre', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enregistreur', models.CharField(default='test', max_length=5)),
                ('Otites_fréquentes', models.BooleanField()),
                ('Angines_fréquentes', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(blank=True, max_length=50, null=True)),
                ('sexe', models.BooleanField()),
                ('avatar', models.ImageField(upload_to='')),
                ('image_AN', models.ImageField(upload_to='')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolResearch.Classe')),
                ('questionnaire', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolResearch.Questionnaire')),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(default='test', max_length=5)),
                ('titre', models.CharField(max_length=50)),
                ('Questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolResearch.Questionnaire')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolResearch.Ecole'),
        ),
    ]
