# Generated by Django 2.2.10 on 2020-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolResearch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentaire',
            old_name='Questionnaire',
            new_name='questionnaire',
        ),
    ]
