# Generated by Django 2.2.10 on 2020-10-16 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolResearch', '0002_auto_20201013_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='filiere',
            new_name='filliere',
        ),
        migrations.RenameField(
            model_name='classe',
            old_name='titre',
            new_name='nom',
        ),
    ]
