# Generated by Django 2.2.10 on 2020-10-17 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolResearch', '0003_auto_20201016_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='image_AN',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolResearch.Questionnaire'),
        ),
        migrations.AlterField(
            model_name='eleve',
            name='sexe',
            field=models.CharField(max_length=1),
        ),
    ]
