# Generated by Django 2.2.10 on 2020-10-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolResearch', '0004_auto_20201017_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='Angines_fréquentes',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='Otites_fréquentes',
            field=models.CharField(max_length=3),
        ),
    ]
